# Site settings
title: N- digital concierges
email: team@thisisn.com
description: > # this means to ignore newlines until "baseurl:"
  Digital concierges - intelligent systems that converse with people with a 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thisisN.com" # the base hostname & protocol for your site
twitter_username: brunorocca
github_username:  productteams

# Build settings
markdown: kramdown
